### ISSUE TITLE
DomainTest中domain结构和官网不一致

### ISSUE THREAD

**Issue by chcodex** [uncle-lv/JRasa#1]
源码中:{
"version": "3.1",
"session_config": {
"session_expiration_time": 60,
"carry_over_slots_to_new_session": true
},
"intents": [
{
"chitchat": {
"use_entities": ["address", "date"]
}
}, 
"deny",
"goodbye",
"greet"
],
"entities": ["address", "date"],
"slots": {
"address": {
"type": "text",
"influence_conversation": false,
"mappings": [{"entity": "address", "type": "from_entity"}]},
"date": {
"type": "text",
"influence_conversation": false,
"mappings": [{"entity": "date", "type": "from_entity"}]}
}, 
"responses": {
"utter_greet": [{"text": "您好"}], 
"utter_goodbye": [{"text": "再见！"}],
"utter_default": [{"text": "我不明白您说的话"}],
"utter_chitchat/whoyouare": [{"text": "你好，我是Rasa，一个智能对话机器人。"}]
},
"actions": [
"utter_goodbye",
"utter_greet",
"utter_default",
"utter_chitchat"
],
"forms": {
"ask_form": {"required_slots": ["address", "date"], "ignored_intents": ["goodbye"]}
}
}

官网:
{
  "next_action": "string",
  "sender_id": "string",
  "tracker": {
    "conversation_id": "default",
    "slots": [
      {
        "slot_name": "slot_value"
      }
    ],
    "latest_message": {
      "entities": [
        {
          "start": 0,
          "end": 0,
          "value": "string",
          "entity": "string",
          "confidence": 0
        }
      ],
      "intent": {
        "confidence": 0.6323,
        "name": "greet"
      },
      "intent_ranking": [
        {
          "confidence": 0.6323,
          "name": "greet"
        }
      ],
      "text": "Hello!"
    },
    "latest_event_time": 1537645578.314389,
    "followup_action": "string",
    "paused": false,
    "events": [
      {
        "event": "user",
        "timestamp": null,
        "metadata": {
          "arbitrary_metadata_key": "some string",
          "more_metadata": 1
        },
        "text": "string",
        "input_channel": "string",
        "message_id": "string",
        "parse_data": {
          "entities": [
            {
              "start": 0,
              "end": 0,
              "value": "string",
              "entity": "string",
              "confidence": 0
            }
          ],
          "intent": {
            "confidence": 0.6323,
            "name": "greet"
          },
          "intent_ranking": [
            {
              "confidence": 0.6323,
              "name": "greet"
            }
          ],
          "text": "Hello!"
        }
      }
    ],
    "latest_input_channel": "rest",
    "latest_action_name": "action_listen",
    "latest_action": {
      "action_name": "string",
      "action_text": "string"
    },
    "active_loop": {
      "name": "restaurant_form"
    }
  },
  "domain": {
    "config": {
      "store_entities_as_slots": false
    },
    "intents": [
      {
        "property1": {
          "use_entities": true
        },
        "property2": {
          "use_entities": true
        }
      }
    ],
    "entities": [
      "person",
      "location"
    ],
    "slots": {
      "property1": {
        "auto_fill": true,
        "initial_value": "string",
        "type": "string",
        "values": [
          "string"
        ]
      },
      "property2": {
        "auto_fill": true,
        "initial_value": "string",
        "type": "string",
        "values": [
          "string"
        ]
      }
    },
    "responses": {
      "property1": {
        "text": "string"
      },
      "property2": {
        "text": "string"
      }
    },
    "actions": [
      "action_greet",
      "action_goodbye",
      "action_listen"
    ]
  }
}

**Comment by chcodex** [comment]
具体为forms和intents结构

**Comment by uncle-lv** [comment]
官方api[文档](https://rasa.com/docs/rasa/pages/http-api)吗？他们很久没有更新过了，这个结构我是参照实际的json数据写的

**Comment by chcodex** [comment]
实际的json我基于2.8.14 看了也和你的设计不同{
  "next_action": "action_weather_form_submit",
  "sender_id": "cbf39bac9122410b964c7e996a1a6753",
  "tracker": {
    "sender_id": "cbf39bac9122410b964c7e996a1a6753",
    "slots": {
      "address": "北京",
      "date-time": "明天",
      "requested_slot": null,
      "session_started_metadata": null
    },
    "latest_message": {
      "intent": {
        "id": -4517285597284029839,
        "name": "weather",
        "confidence": 0.9999991655349731
      },
      "entities": [
        {
          "entity": "address",
          "start": 2,
          "end": 4,
          "confidence_entity": 0.9996744394302368,
          "value": "北京",
          "extractor": "DIETClassifier"
        },
        {
          "entity": "date-time",
          "start": 4,
          "end": 6,
          "confidence_entity": 0.9997091889381409,
          "value": "明天",
          "extractor": "DIETClassifier"
        }
      ],
      "text": "查询北京明天的天气",
      "message_id": "03634d08d6d8455d90596f5d319832ca",
      "metadata": {},
      "intent_ranking": [
        {
          "id": -4517285597284029839,
          "name": "weather",
          "confidence": 0.9999991655349731
        },
        {
          "id": -8391847190126310097,
          "name": "greet",
          "confidence": 1.8877756247093203E-7
        },
        {
          "id": 4861638968527993254,
          "name": "goodbye",
          "confidence": 1.7885906800074736E-7
        },
        {
          "id": -8072709068067298270,
          "name": "info_date",
          "confidence": 1.702736227571222E-7
        },
        {
          "id": 1938829062832901588,
          "name": "info_address",
          "confidence": 1.1873724048427903E-7
        },
        {
          "id": 6937403598619671411,
          "name": "deny",
          "confidence": 7.812835178810928E-8
        },
        {
          "id": 5609590596670507261,
          "name": "affirm",
          "confidence": 5.914018075259264E-8
        },
        {
          "id": -6804887092759000876,
          "name": "stop",
          "confidence": 4.414929577478688E-8
        },
        {
          "id": -4583512726923959506,
          "name": "chitchat",
          "confidence": 3.569309470208282E-8
        }
      ],
      "response_selector": {
        "all_retrieval_intents": [
          "chitchat"
        ],
        "default": {
          "response": {
            "id": 6266574829498604044,
            "responses": [
              {
                "text": "你好，我是Silly，一个专注天气预报的对话机器人。"
              }
            ],
            "response_templates": [
              {
                "text": "你好，我是Silly，一个专注天气预报的对话机器人。"
              }
            ],
            "confidence": 0.9999998807907104,
            "intent_response_key": "chitchat/whoyouare",
            "utter_action": "utter_chitchat/whoyouare",
            "template_name": "utter_chitchat/whoyouare"
          },
          "ranking": [
            {
              "id": 6266574829498604044,
              "confidence": 0.9999998807907104,
              "intent_response_key": "chitchat/whoyouare"
            },
            {
              "id": -7650615450657241683,
              "confidence": 1.220452503503111E-7,
              "intent_response_key": "chitchat/whatyoucando"
            }
          ]
        }
      }
    },
    "latest_event_time": 1.689237751067696E9,
    "followup_action": null,
    "paused": false,
    "events": [
      {
        "event": "session_started",
        "timestamp": 1.6892377456977186E9
      },
      {
        "event": "action",
        "timestamp": 1.6892377456977334E9,
        "name": "action_listen",
        "policy": null,
        "confidence": null,
        "action_text": null,
        "hide_rule_turn": false
      },
      {
        "event": "user",
        "timestamp": 1.689237751066734E9,
        "text": "查询北京明天的天气",
        "parse_data": {
          "intent": {
            "id": -4517285597284029839,
            "name": "weather",
            "confidence": 0.9999991655349731
          },
          "entities": [
            {
              "entity": "address",
              "start": 2,
              "end": 4,
              "confidence_entity": 0.9996744394302368,
              "value": "北京",
              "extractor": "DIETClassifier"
            },
            {
              "entity": "date-time",
              "start": 4,
              "end": 6,
              "confidence_entity": 0.9997091889381409,
              "value": "明天",
              "extractor": "DIETClassifier"
            }
          ],
          "text": "查询北京明天的天气",
          "message_id": "03634d08d6d8455d90596f5d319832ca",
          "metadata": {},
          "intent_ranking": [
            {
              "id": -4517285597284029839,
              "name": "weather",
              "confidence": 0.9999991655349731
            },
            {
              "id": -8391847190126310097,
              "name": "greet",
              "confidence": 1.8877756247093203E-7
            },
            {
              "id": 4861638968527993254,
              "name": "goodbye",
              "confidence": 1.7885906800074736E-7
            },
            {
              "id": -8072709068067298270,
              "name": "info_date",
              "confidence": 1.702736227571222E-7
            },
            {
              "id": 1938829062832901588,
              "name": "info_address",
              "confidence": 1.1873724048427903E-7
            },
            {
              "id": 6937403598619671411,
              "name": "deny",
              "confidence": 7.812835178810928E-8
            },
            {
              "id": 5609590596670507261,
              "name": "affirm",
              "confidence": 5.914018075259264E-8
            },
            {
              "id": -6804887092759000876,
              "name": "stop",
              "confidence": 4.414929577478688E-8
            },
            {
              "id": -4583512726923959506,
              "name": "chitchat",
              "confidence": 3.569309470208282E-8
            }
          ],
          "response_selector": {
            "all_retrieval_intents": [
              "chitchat"
            ],
            "default": {
              "response": {
                "id": 6266574829498604044,
                "responses": [
                  {
                    "text": "你好，我是Silly，一个专注天气预报的对话机器人。"
                  }
                ],
                "response_templates": [
                  {
                    "text": "你好，我是Silly，一个专注天气预报的对话机器人。"
                  }
                ],
                "confidence": 0.9999998807907104,
                "intent_response_key": "chitchat/whoyouare",
                "utter_action": "utter_chitchat/whoyouare",
                "template_name": "utter_chitchat/whoyouare"
              },
              "ranking": [
                {
                  "id": 6266574829498604044,
                  "confidence": 0.9999998807907104,
                  "intent_response_key": "chitchat/whoyouare"
                },
                {
                  "id": -7650615450657241683,
                  "confidence": 1.220452503503111E-7,
                  "intent_response_key": "chitchat/whatyoucando"
                }
              ]
            }
          }
        },
        "input_channel": "rasa",
        "message_id": "03634d08d6d8455d90596f5d319832ca",
        "metadata": {}
      },
      {
        "event": "slot",
        "timestamp": 1.6892377510667555E9,
        "name": "address",
        "value": "北京"
      },
      {
        "event": "slot",
        "timestamp": 1.6892377510667586E9,
        "name": "date-time",
        "value": "明天"
      },
      {
        "event": "user_featurization",
        "timestamp": 1.6892377510676653E9,
        "use_text_for_featurization": false
      },
      {
        "event": "action",
        "timestamp": 1.6892377510676746E9,
        "name": "weather_form",
        "policy": "policy_0_RulePolicy",
        "confidence": 1.0,
        "action_text": null,
        "hide_rule_turn": false
      },
      {
        "event": "active_loop",
        "timestamp": 1.6892377510676847E9,
        "name": "weather_form"
      },
      {
        "event": "slot",
        "timestamp": 1.689237751067688E9,
        "name": "address",
        "value": "北京"
      },
      {
        "event": "slot",
        "timestamp": 1.68923775106769E9,
        "name": "date-time",
        "value": "明天"
      },
      {
        "event": "slot",
        "timestamp": 1.6892377510676918E9,
        "name": "address",
        "value": "北京"
      },
      {
        "event": "slot",
        "timestamp": 1.689237751067693E9,
        "name": "date-time",
        "value": "明天"
      },
      {
        "event": "slot",
        "timestamp": 1.6892377510676947E9,
        "name": "requested_slot",
        "value": null
      },
      {
        "event": "active_loop",
        "timestamp": 1.689237751067696E9,
        "name": null
      }
    ],
    "latest_input_channel": "rasa",
    "active_loop": {},
    "latest_action": {
      "action_name": "weather_form"
    },
    "latest_action_name": "weather_form"
  },
  "domain": {
    "config": {
      "store_entities_as_slots": true
    },
    "session_config": {
      "session_expiration_time": 60,
      "carry_over_slots_to_new_session": true
    },
    "intents": [
      {
        "chitchat": {
          "is_retrieval_intent": true,
          "use_entities": true
        }
      },
      {
        "goodbye": {
          "use_entities": true
        }
      },
      {
        "greet": {
          "use_entities": true
        }
      },
      {
        "weather": {
          "use_entities": true
        }
      },
      {
        "deny": {
          "use_entities": true
        }
      },
      {
        "stop": {
          "use_entities": true
        }
      },
      {
        "affirm": {
          "use_entities": true
        }
      },
      {
        "info_date": {
          "use_entities": true
        }
      },
      {
        "info_address": {
          "use_entities": true
        }
      }
    ],
    "entities": [
      "address",
      "date-time"
    ],
    "slots": {
      "address": {
        "type": "rasa.shared.core.slots.TextSlot",
        "initial_value": null,
        "auto_fill": true,
        "influence_conversation": false
      },
      "date-time": {
        "type": "rasa.shared.core.slots.TextSlot",
        "initial_value": null,
        "auto_fill": true,
        "influence_conversation": false
      }
    },
    "responses": {
      "utter_greet": [
        {
          "text": "你好，请说出需要提供天气预测服务的地点和时间"
        }
      ],
      "utter_goodbye": [
        {
          "text": "再见！"
        }
      ],
      "utter_ask_address": [
        {
          "text": "想查询哪里的天气呢？"
        }
      ],
      "utter_ask_date-time": [
        {
          "text": "想查询什么时候的天气呢？"
        }
      ],
      "utter_ask_continue": [
        {
          "text": "是否要继续？"
        }
      ],
      "utter_default": [
        {
          "text": "系统不明白您说的话，请换个说法。"
        }
      ],
      "utter_chitchat/whoyouare": [
        {
          "text": "你好，我是Silly，一个专注天气预报的对话机器人。"
        }
      ],
      "utter_chitchat/whatyoucando": [
        {
          "text": "我能帮你查找中国大陆地区城市级别的当下和未来两天的天气情况。"
        }
      ]
    },
    "actions": [
      "action_weather_form_submit",
      "respond_chitchat",
      "utter_ask_address",
      "utter_ask_continue",
      "utter_ask_date-time",
      "utter_chitchat",
      "utter_default",
      "utter_goodbye",
      "utter_greet"
    ],
    "forms": {
      "weather_form": {
        "ignored_intents": [],
        "required_slots": {
          "address": [
            {
              "entity": "address",
              "type": "from_entity"
            }
          ],
          "date-time": [
            {
              "entity": "date-time",
              "type": "from_entity"
            }
          ]
        }
      }
    },
    "e2e_actions": []
  },
  "version": "2.8.14"
}

**Comment by uncle-lv** [comment]
domain.yml我是基于3.1版本写的，目前不考虑向前兼容
